# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CG.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DICOM import *

class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(547, 385)
        Mainwindow.setAutoFillBackground(False)
        
        self.centralwidget = QtWidgets.QWidget(Mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 80, 101, 71))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 80, 101, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(90, 190, 361, 41))
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setStyleSheet("")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setMinimum(10)
        self.horizontalSlider.setMaximum(500)

        Mainwindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(Mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 26))
        self.menubar.setStyleSheet("background-color: rgb(251, 252, 255);")
        self.menubar.setObjectName("menubar")
        self.menufolder = QtWidgets.QMenu(self.menubar)
        self.menufolder.setObjectName("menufolder")
        Mainwindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(Mainwindow)
        self.statusbar.setObjectName("statusbar")
        Mainwindow.setStatusBar(self.statusbar)
        self.act = QtWidgets.QAction("Open")
        self.menubar.addAction(self.act)
        self.act.triggered.connect(self.open_folder)

        self.retranslateUi(Mainwindow)
        self.event_listeners()
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)
        
    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "MainWindow"))
        self.pushButton.setText(_translate("Mainwindow", "Surface Render"))
        self.pushButton_2.setText(_translate("Mainwindow", "Ray Render"))
    
    def event_listeners(self):
        self.horizontalSlider.sliderReleased.connect(lambda : self.rend.surface_render(self.horizontalSlider.value()))
        self.pushButton.clicked.connect(lambda : self.rend.surface_render(self.horizontalSlider.value()))
        self.pushButton_2.clicked.connect(lambda : self.rend.ray_render())

    
    def open_folder(self):
        folder = QtWidgets.QFileDialog.getExistingDirectory(None, 'Select Folder') or None
        if folder is not None:
            self.rend = DICOM_Renderer(folder)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mainwindow = QtWidgets.QMainWindow()
    ui = Ui_Mainwindow()
    ui.setupUi(Mainwindow)
    Mainwindow.show()
    sys.exit(app.exec_())